name: Execute notebooks top to bottom to ensure no errors.
on:
  push:
  pull_request:
  schedule:
      - cron: '00 4 * * *'  # daily at 4AM 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout files in repo.
      uses: actions/checkout@main

    - name: Set up Python 3.x.
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dev requirements.
      shell: bash -l {0}
      run: |
        set -vxeuo pipefail
        python -m pip install -r binder/requirements-dev
        python -m pip install list

    - name: Execute notebooks with papermill.
      shell: bash -l {0}
      run: |
        set -vxeuo pipefail
        # The notebook output will be directed to /dev/null but if there is any
        # error execution will stop and the error will be shown in stderr (and
        # hence in the logs).
        jupyter-repo2docker . pip install papermill && papermill *.ipynb - > /dev/null
